version: '3.5'
services:
 redis:
  image: redis:latest
  container_name: wxwl_redis
  ports:
    - "6379:6379"
  volumes:
    - ./data:/data
    # 替换容器内redis.conf
    - ./conf/redis.conf:/usr/local/etc/redis/redis.conf

  docker run --name base-redis -p 6379:6379 -v /opt/redis/docker-conf/redis.conf:/opt/redis/conf/redis.conf -v
